package com.example.cnpm.main.frame;

import com.example.cnpm.main.dao.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.example.cnpm.main.util.NguoiDangKi;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;

/**
 *
 * @author DELL
 */
public class GDQuanLiNDK extends javax.swing.JFrame  implements ActionListener{
    DefaultTableModel tableModel;
    ArrayList<NguoiDangKi> NList = DBContext.selectQuery();
       /**
     * Creates new form GDQuanLiNDK */
       private int selectIndex1;
    public GDQuanLiNDK(int mode) {
        initComponents();
        btnChinhsua.addActionListener(this);
        btnFind.addActionListener(this);
        btnThem.addActionListener(this);
        btnHuydk.addActionListener(this);
        tableModel = (DefaultTableModel) jTable1.getModel();
        showMem();
        setLocationRelativeTo(null);
        this.setTitle("Giao di\u1EC7n qu\u1EA3n l\u00FD kh\u00E1ch h\u00E0ng");
        
        checkMode(mode);
    }
    private void showMem(){
       
        tableModel.setRowCount(0);
        for(NguoiDangKi ndk : NList){
        tableModel.addRow(new Object[]{ndk.getName(),ndk.getAddress(),ndk.getPhoneNumber()
        ,ndk.getCMND(),ndk.getTimeUse(),ndk.getGioitinh()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        btnThem = new javax.swing.JButton();
        btnChinhsua = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnHuydk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnThem.setText("N\u1EEF");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnChinhsua.setText("Ch\u1EC9nh s\u1EEDa");
        btnChinhsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhsuaActionPerformed(evt);
            }
        });

        btnFind.setText("T\u00ECm ki\u1EBFm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnHuydk.setText("Hu\u1EF7 \u0111\u0103ng k\u00FD");
        btnHuydk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuydkActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "H\u1ECD v\u00E0 t\u00EAn","\u0110\u1ECBa ch\u1EC9", "S\u0110T", "CMND", "Ng\u00E0y sinh","Gi\u1EDBi t\u00EDnh"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnHome.setText("Trang ch\u1EE7");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel = new JLabel("QU\u1EA2N L\u00DD TH\u00D4NG TIN KH\u00C1CH H\u00C0NG");
        lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(34)
        			.addComponent(btnThem, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        			.addGap(146)
        			.addComponent(btnChinhsua)
        			.addGap(153)
        			.addComponent(btnHome)
        			.addGap(133)
        			.addComponent(btnHuydk)
        			.addPreferredGap(ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
        			.addComponent(btnFind)
        			.addGap(111))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(421, Short.MAX_VALUE)
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE)
        			.addGap(366))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnThem)
        				.addComponent(btnChinhsua)
        				.addComponent(btnHuydk)
        				.addComponent(btnFind)
        				.addComponent(btnHome))
        			.addPreferredGap(ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnHuydkActionPerformed(java.awt.event.ActionEvent evt) {                                         
         int selectedindex = jTable1.getSelectedRow();
           if(selectedindex == -1){
            JOptionPane.showMessageDialog(rootPane,"Vui l\u00F2ng ch\u1ECDn m\u1ED9t d\u00F2ng !");
           }
           else if(NList.size()==0){
                JOptionPane.showMessageDialog(rootPane,"Kh\u00F4ng c\u00F3 th\u00F4ng tin !!");
           } else{
                int option = JOptionPane.showConfirmDialog(rootPane, "B\u1EA1n c\u00F3 mu\u1ED1n xo\u00E1 kh\u00E1ch h\u00E0ng n\u00E0y kh\u00F4ng ?");
                if(selectedindex >=0){
                    NguoiDangKi ndk= NList.get(selectedindex);
                   
                if(option ==0){
               DBContext.delete(ndk.getCMND());
                NList.remove(selectedindex); }
                showMem();
           }
           }     
           
    }                                        

    private void btnChinhsuaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
            /*  int select = jTable1.getSelectedRow();
            if (select == -1) {
                JOptionPane.showMessageDialog(rootPane, "Xin vui lÃƒÂ²ng chÃ¡Â»ï¿½n dÃƒÂ²ng cÃ¡ÂºÂ§n sÃ¡Â»Â­a: ");
            } else {
                 NguoiDangKi ndk= NList.get(select);
               DBContext.UpdateMem(ndk);
                jTable1.setModel(tableModel);
              JOptionPane.showMessageDialog(rootPane, "CÃ¡ÂºÂ­p nhÃ¡ÂºÂ­t xong");
            }
        */
            selectIndex1 =jTable1.getSelectedRow();
            if(NList.size()==0){
                JOptionPane.showMessageDialog(rootPane, "Kh\u00F4ng c\u00F3 th\u00F4ng tin, vui l\u00F2ng th\u00EAm th\u00F4ng tin ! ");
            }
            else if(selectIndex1 == -1){
                 JOptionPane.showMessageDialog(rootPane, "Xin vui lÃ²ng chá»�n dÃ²ng cáº§n sá»­a: ");
            } else{ 
                if(selectIndex1 >=0){
                    NguoiDangKi ndk= NList.get(selectIndex1);
                    GDChinhsuaDK edit = new GDChinhsuaDK();
                    edit.setEditData(NList.get(selectIndex1));
     
              //      NList.remove(selectIndex1);
                    edit.actionPerformed(evt);                  
                    edit.setVisible(true);
                      }
                showMem();
              
             
 
            }
    }                                           

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       
        String input = JOptionPane.showInputDialog(this,"Vui l\u00F2ng nh\u1EADp t\u00EAn c\u1EA7n t\u00ECm ki\u1EBFm:");
        if(input != null && input.length() > 0) {
            NList = DBContext.findByname(input);
            
           tableModel.setRowCount(0);
        NList.forEach( (ndk)-> {
        tableModel.addRow(new Object[]{ndk.getName(),ndk.getAddress(),ndk.getPhoneNumber()
        ,ndk.getCMND(),ndk.getTimeUse(),ndk.getGioitinh()});}
        );}
           else {
            showMem();
        }    
    
        
    }                                       

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
         new BaoCaoHoatDong().setVisible(true);
          this.dispose();
    }                                       
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDQuanLiNDK(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnChinhsua;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHuydk;
    private javax.swing.JButton btnThem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
      if(e.getSource().equals(btnThem)){
          btnThemClick();
      }
      
  //    else if (e.getSource().equals((btnChinhsua))){
 //         btnChinhsuaClick();
    //  }
    }
    public void btnThemClick(){
    	GDThemNguoiDK newFrame = new GDThemNguoiDK();
    	newFrame.setVisible(true);
        this.dispose();
    }
  
    public void btnChinhsuaClick(){
        this.dispose();
    }
    
    private void checkMode(int mode) {
    	if(mode == 0) return;
    	btnChinhsua.setVisible(false);
    	btnHome.setVisible(false);
    	btnHuydk.setVisible(false);
    }
}

