package com.example.cnpm.main.frame;

import com.example.cnpm.main.dao.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.example.cnpm.main.util.NguoiDangKi;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;

/**
 *
 * @author DELL
 */
public class GDQuanLiNDK extends javax.swing.JFrame  implements ActionListener{
    DefaultTableModel tableModel;
    ArrayList<NguoiDangKi> NList = DBContext.selectQuery();
       /**
     * Creates new form GDQuanLiNDK */
       private int selectIndex1;
    public GDQuanLiNDK(int mode) {
        initComponents();
        btnChinhsua.addActionListener(this);
        btnFind.addActionListener(this);
        btnThem.addActionListener(this);
        btnHuydk.addActionListener(this);
        tableModel = (DefaultTableModel) jTable1.getModel();
        showMem();
        setLocationRelativeTo(null);
        this.setTitle("Giao diện quản lí thông tin cá nhân ");
        
        checkMode(mode);
    }
    private void showMem(){
       
        tableModel.setRowCount(0);
        for(NguoiDangKi ndk : NList){
        tableModel.addRow(new Object[]{ndk.getName(),ndk.getAddress(),ndk.getPhoneNumber()
        ,ndk.getCMND(),ndk.getTimeUse(),ndk.getGioitinh()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        btnThem = new javax.swing.JButton();
        btnChinhsua = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnHuydk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnChinhsua.setText("Chỉnh sửa");
        btnChinhsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhsuaActionPerformed(evt);
            }
        });

        btnFind.setText("Tìm kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnHuydk.setText("Hủy ĐK");
        btnHuydk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuydkActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Họ và tên","Địa chỉ", "SĐT", "CMND", "Ngày sinh","Giới tính"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnHome.setText("Trang chính");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        
        JLabel lblNewLabel = new JLabel("Qu\u1EA3n L\u00ED th\u00F4ng tin c\u00E1 nh\u00E2n ng\u01B0\u1EDDi \u0111\u0103ng k\u00ED");
        lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(34)
        			.addComponent(btnThem, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        			.addGap(72)
        			.addComponent(btnChinhsua)
        			.addGap(134)
        			.addComponent(btnHome)
        			.addPreferredGap(ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
        			.addComponent(btnHuydk)
        			.addGap(115)
        			.addComponent(btnFind)
        			.addGap(60))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(301)
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addGap(26)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnThem)
        				.addComponent(btnChinhsua)
        				.addComponent(btnFind)
        				.addComponent(btnHuydk)
        				.addComponent(btnHome))
        			.addPreferredGap(ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnHuydkActionPerformed(java.awt.event.ActionEvent evt) {                                         
         int selectedindex = jTable1.getSelectedRow();
           if(selectedindex == -1){
            JOptionPane.showMessageDialog(rootPane,"Please choose a line!");
           }
           else if(NList.size()==0){
                JOptionPane.showMessageDialog(rootPane,"Không có thông tin !");
           } else{
                int option = JOptionPane.showConfirmDialog(rootPane, "Do you want to delete this item?");
                if(selectedindex >=0){
                    NguoiDangKi ndk= NList.get(selectedindex);
                   
                if(option ==0){
               DBContext.delete(ndk.getCMND());
                NList.remove(selectedindex); }
                showMem();
           }
           }     
           
    }                                        

    private void btnChinhsuaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
            /*  int select = jTable1.getSelectedRow();
            if (select == -1) {
                JOptionPane.showMessageDialog(rootPane, "Xin vui lÃ²ng chá»�n dÃ²ng cáº§n sá»­a: ");
            } else {
                 NguoiDangKi ndk= NList.get(select);
               DBContext.UpdateMem(ndk);
                jTable1.setModel(tableModel);
              JOptionPane.showMessageDialog(rootPane, "Cáº­p nháº­t xong");
            }
        */
            selectIndex1 =jTable1.getSelectedRow();
            if(NList.size()==0){
                JOptionPane.showMessageDialog(rootPane, "Không có thông tin! Vui lòng thêm thông tin!");
            }
            else if(selectIndex1 == -1){
                 JOptionPane.showMessageDialog(rootPane, "Xin vui lòng chọn dòng cần sửa: ");
            } else{ 
                if(selectIndex1 >=0){
                    NguoiDangKi ndk= NList.get(selectIndex1);
                    GDChinhsuaDK edit = new GDChinhsuaDK();
                    edit.setEditData(NList.get(selectIndex1));
     
              //      NList.remove(selectIndex1);
                    edit.actionPerformed(evt);                  
                    edit.setVisible(true);
                      }
                showMem();
              
             
 
            }
    }                                           

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       
        String input = JOptionPane.showInputDialog(this,"Enter name to search:");
        if(input != null && input.length() > 0) {
            NList = DBContext.findByname(input);
            
           tableModel.setRowCount(0);
        NList.forEach( (ndk)-> {
        tableModel.addRow(new Object[]{ndk.getName(),ndk.getAddress(),ndk.getPhoneNumber()
        ,ndk.getCMND(),ndk.getTimeUse(),ndk.getGioitinh()});}
        );}
           else {
            showMem();
        }    
    
        
    }                                       

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
         new BaoCaoHoatDong().setVisible(true);
          this.dispose();
    }                                       
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDQuanLiNDK(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnChinhsua;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHuydk;
    private javax.swing.JButton btnThem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
      if(e.getSource().equals(btnThem)){
          btnThemClick();
      }
      
  //    else if (e.getSource().equals((btnChinhsua))){
 //         btnChinhsuaClick();
    //  }
    }
    public void btnThemClick(){
    	GDThemNguoiDK newFrame = new GDThemNguoiDK();
    	newFrame.setVisible(true);
        this.dispose();
    }
  
    public void btnChinhsuaClick(){
        this.dispose();
    }
    
    private void checkMode(int mode) {
    	if(mode == 0) return;
    	btnChinhsua.setVisible(false);
    	//btnHome.setVisible(false);
    	btnHuydk.setVisible(false);
    }
}

